export const PROCEDURE_TYPES = [
  { key: 'carboxytherapy', ka: 'კარბოქსითერაპია', en: 'Carboxytherapy' },
  { key: 'laser_resurfacing', ka: 'FOTONA სახის კანის აბლაცია – აპარატურული პილინგი', en: 'Fotona facial skin ablation – device peel' },
  { key: 'tattoo_removal', ka: 'ტატუს მოცილება', en: 'Tattoo removal' },
  { key: 'diamond_dermabrasion', ka: 'ალმასური დერმაბრაზია', en: 'Diamond dermabrasion' },
  { key: 'cold_plasma', ka: 'ცივი პლაზმა', en: 'Cold plasma' },
  { key: 'lip_rejuvenation_liplase', ka: 'ტუჩის გაახალგაზრდავება – FOTONA LIPLASE', en: 'Lip rejuvenation – Fotona LipLase' },
  { key: 'emsculpt_body_sculpting', ka: 'სხეულის და კუნთის მოდელირება – EMSCULPT', en: 'Body and muscle sculpting – Emsculpt' },
  { key: 'electrocoagulation', ka: 'ელექტროკოაგულაცია', en: 'Electrocoagulation' },
  { key: 'photorejuvenation_ipl', ka: 'ფოტოგაახალგაზრდავება – VIORA-IPL', en: 'Photorejuvenation – Viora IPL' },
  { key: 'microneedling', ka: 'მიკრონიდლინგი (ზოგადი)', en: 'Microneedling (general)' },
  { key: 'laser_hair_removal', ka: 'ლაზერული ეპილაცია – DEKA', en: 'Laser hair removal – Deka' },
  { key: 'carbon_peel', ka: 'კარბონის პილინგი – Spectra XT', en: 'Carbon peel – Spectra XT' },
  { key: 'lpg_massage', ka: 'LPG – მასაჟი', en: 'LPG massage' },
  { key: 'fotona_4d_facial', ka: 'სახის ლაზერული გაახალგაზრდავება – FOTONA 4D', en: 'Laser facial rejuvenation – Fotona 4D' },
  { key: 'mesotherapy', ka: 'მეზოთერაპია', en: 'Mesotherapy' },
  { key: 'botox_injection', ka: 'ბოტულინოთერაპია', en: 'Botulinum therapy' },
  { key: 'biorevitalisation', ka: 'ბიორევიტალიზაცია', en: 'Biorevitalisation' },
  { key: 'prp_facial', ka: 'პლაზმოთერაპია / PRP — სახის მიმართულებით', en: 'PRP therapy – face' },
  { key: 'prp_body', ka: 'პლაზმოთერაპია / PRP — სხეულის მიმართულებით', en: 'PRP therapy – body' },
  { key: 'hydrafacial', ka: 'ჰაიდრაფეიშალი (HydraFacial)', en: 'HydraFacial' },
  { key: 'hyperhidrosis_treatment', ka: 'ჰიპერჰიდროზი – ჭარბოფლიანობის მკურნალობა', en: 'Hyperhidrosis treatment' },
  { key: 'poly_lactic_acid', ka: 'პოლირძემჟავა', en: 'Poly-L-lactic acid' },
  { key: 'contour_plasty', ka: 'სახისა და სხეულის კონტურული პლასტიკა', en: 'Facial and body contouring' },
  { key: 'facial_cleansing', ka: 'სახის კანის წმენდა', en: 'Facial skin cleansing' },
  { key: 'exosome_therapy', ka: 'ეგზოსომური თერაპია (დეროვან უჯრედებზე დაფუძნებული მკურნალობა)', en: 'Exosome therapy' },
  { key: 'acne_treatment', ka: 'აკნეს მკურნალობა', en: 'Acne treatment' },
  { key: 'rf_microneedling', ka: 'RF ფრაქციული მიკრონიდლინგი', en: 'RF fractional microneedling' },
  { key: 'dermapen', ka: 'დერმაპენი (მიკრონიდლინგი)', en: 'Dermapen microneedling' },
  { key: 'dermal_filler', ka: 'ჰიალურონის მჟავის ინექციები (ფილერები)', en: 'Hyaluronic acid injections (fillers)' },
  { key: 'chemical_peel', ka: 'პილინგი (Peeling)', en: 'Peeling' },
  { key: 'ultherapy_hifu', ka: 'ულთერაპია/Hi-Fu (Ultherapy/Hi-Fu)', en: 'Ultherapy / Hi-Fu' },
  { key: 'pigmentation_scar_treatment', ka: 'ჰიპერპიგმენტაციისა და ნაწიბურების მკურნალობა', en: 'Hyperpigmentation and scar treatment' },
  { key: 'phototherapy', ka: 'ფოტოთერაპია', en: 'Phototherapy' },
  { key: 'mammoplasty', ka: 'მამოპლასტიკა', en: 'Mammoplasty' },
  { key: 'blepharoplasty', ka: 'ბლეფაროპლასტიკა', en: 'Blepharoplasty' },
  { key: 'brow_lift', ka: 'წარბების ლიფტინგი', en: 'Brow lift' },
  { key: 'liposuction', ka: 'ლიპოსაქცია', en: 'Liposuction' },
  { key: 'femoroplasty', ka: 'ფემოროპლასტიკა', en: 'Femoroplasty (thigh lift)' },
  { key: 'torsoplasty', ka: 'ტორსოპლასტიკა', en: 'Torsoplasty' },
  { key: 'facelift', ka: 'სახის ლიფტინგი', en: 'Facelift' },
  { key: 'abdominoplasty', ka: 'აბდომინოპლასტიკა', en: 'Abdominoplasty' },
  { key: 'brachioplasty', ka: 'ბრაქიოპლასტიკა', en: 'Brachioplasty (arm lift)' },
  { key: 'gynecomastia_surgery', ka: 'გინეკომასტია', en: 'Gynecomastia' },
  { key: 'liposculpture', ka: 'ლიპოსკულპტურა', en: 'Liposculpture' },
  { key: 'rhinoplasty', ka: 'რინოპლასტიკა', en: 'Rhinoplasty' },
  { key: 'labiaplasty', ka: 'ლაბიოპლასტიკა', en: 'Labiaplasty' },
  { key: 'perineoplasty', ka: 'პერინეოპლასტიკა', en: 'Perineoplasty' },
  { key: 'vaginoplasty', ka: 'საშოს პლასტიკა', en: 'Vaginoplasty' },
  { key: 'clitoral_hood_reduction', ka: 'კლიტორის ჰუდის რეზექცია', en: 'Clitoral hood reduction' },
  { key: 'stress_incontinence_treatment', ka: 'I ხარისხის შარდის სტრესული შეუკავებლობის მკურნალობა', en: 'Grade I stress urinary incontinence treatment' },
  { key: 'vaginal_introitus_narrowing', ka: 'საშოს შესავლის დავიწროვება', en: 'Vaginal introitus narrowing' },
  { key: 'chemical_peel_gynecological', ka: 'ქიმიური პილინგი (გინეკოლოგიური მიმართულებით)', en: 'Chemical peel (gynaecological)' },
  { key: 'prp_gynecological', ka: 'პლაზმოლიფტინგი (PRP) — გინეკოლოგიური მიმართულებით', en: 'PRP plasma lifting (gynaecological)' },
  { key: 'g_spot_augmentation', ka: 'G-წერტილის აუგმენტაცია', en: 'G-spot augmentation' },
  { key: 'labia_majora_plasty', ka: 'დიდი სასირცხო ბაგეების პლასტიკა', en: 'Labia majora plasty' },
  { key: 'endovenous_laser_ablation', ka: 'ვენის ლაზერული აბლაცია', en: 'Endovenous laser ablation' },
  { key: 'sclerotherapy', ka: 'სკლეროთერაპია', en: 'Sclerotherapy' },
  { key: 'miniphlebectomy', ka: 'მინიფლებექტომია', en: 'Miniphlebectomy' },
  { key: 'thread_lift', ka: 'APTOS ძაფები', en: 'APTOS threads' },
  { key: 'anti_cellulite_therapy', ka: 'ანტიცელულიტური თერაპია', en: 'Anti-cellulite therapy' },
  { key: 'lymphatic_drainage', ka: 'ლიმფური დრენაჟის თერაპია', en: 'Lymphatic drainage therapy' },
  { key: 'myostimulation', ka: 'მიოსტიმულაცია და კუნთების აღდგენა', en: 'Myostimulation and muscle recovery' },
  { key: 'skin_tightening_therapy', ka: 'კანის გამკვრივების თერაპია', en: 'Skin tightening therapy' },
  { key: 'sagging_skin_recovery', ka: 'მოდუნებული კანის აღდგენა', en: 'Sagging skin recovery' },
  { key: 'body_correction', ka: 'სხეულის კორექციის პროცედურა', en: 'Body correction procedure' },
  { key: 'emslim_body_sculpting', ka: 'Emslim სხეულის სკულპტინგი', en: 'Emslim body sculpting' },
  { key: 'localised_fat_reduction', ka: 'ცხიმის შემცირება ლოკალურად', en: 'Localised fat reduction' },
  { key: 'hair_exosome_therapy', ka: 'თმის ეგზოსომური თერაპია', en: 'Hair exosome therapy' },
  { key: 'hair_mesotherapy', ka: 'თმის მეზოთერაპია (თმის ცვენის მკურნალობა)', en: 'Hair mesotherapy (hair loss treatment)' },
  { key: 'dermatoscopy', ka: 'დერმატოსკოპია', en: 'Dermatoscopy' },
  { key: 'viral_papilloma_removal', ka: 'ვირუსული პაპილომების მოცილება', en: 'Viral papilloma removal' },
  { key: 'seborrheic_keratosis_removal', ka: 'სებორეული კერატომას მოცილება', en: 'Seborrhoeic keratosis removal' },
  { key: 'fibroma_removal', ka: 'ფიბრომას მოცილება', en: 'Fibroma removal' },
  { key: 'lentigo_removal', ka: 'ლენტიგოს მოცილება', en: 'Lentigo removal' },
  { key: 'wart_removal', ka: 'მეჭეჭების მოცილება', en: 'Wart removal' },
  { key: 'demodex_treatment', ka: 'დემოდექსის მკურნალობა', en: 'Demodex treatment' },
  { key: 'rosacea_treatment', ka: 'როზაცეას მკურნალობა', en: 'Rosacea treatment' },
  { key: 'onychomycosis_treatment', ka: 'ონიქომიკოზის (ფრჩხილის სოკოს) მკურნალობა', en: 'Onychomycosis (nail fungus) treatment' },
  { key: 'facial_vascular_lesion_treatment', ka: 'სახის ვასკულარული დაზიანებების მკურნალობა', en: 'Facial vascular lesion treatment' },
  { key: 'non_surgical_blepharoplasty', ka: 'არაქირურგიული ბლეფაროპლასტიკა', en: 'Non-surgical blepharoplasty' },
  { key: 'vector_lift', ka: 'ვექტორ-ლიფტინგი', en: 'Vector lifting' },
  { key: 'lipolytics', ka: 'ლიპოლიტიკები (ინექციური ცხიმის დაშლა)', en: 'Lipolytics (injectable fat dissolving)' },
  { key: 'krf_lifting', ka: 'KRF სახის/სხეულის ლიფტინგი', en: 'KRF face and body lifting' },
  { key: 'shockwave_therapy', ka: 'დინამიური ტალღა (შოკური თერაპია)', en: 'Dynamic wave (shockwave) therapy' },
  { key: 'pressotherapy', ka: 'პრესოთერაპია', en: 'Pressotherapy' },
  { key: 'electrolysis', ka: 'ელექტროლიზი', en: 'Electrolysis' },
  { key: 'seasonal_peels', ka: 'სეზონური პილინგები', en: 'Seasonal peels' },
  { key: 'facial_massage', ka: 'სახის მასაჟი', en: 'Facial massage' },
  { key: 'body_wraps', ka: 'სხეულის შეხვევები', en: 'Body wraps' },
  { key: 'express_spa', ka: 'ექსპრეს სპა პროცედურები', en: 'Express spa treatments' },
  { key: 'general_body_massage', ka: 'ზოგადი სხეულის მასაჟი', en: 'General body massage' },
  // Last on purpose: the catch-all belongs after everything it is a fallback for.
  { key: 'other', ka: 'სხვა', en: 'Other' },
] as const;

export const ANESTHESIA_TYPES = [
  { key: 'general', ka: 'ზოგადი ნარკოზი', en: 'General' },
  { key: 'regional', ka: 'რეგიონული ანესთეზია', en: 'Regional' },
  { key: 'local', ka: 'ადგილობრივი ანესთეზია', en: 'Local' },
  { key: 'sedation', ka: 'სედაცია', en: 'Sedation' },
  { key: 'none', ka: 'ანესთეზიის გარეშე', en: 'None' },
] as const;

export const INTENSITY_LEVELS = [
  { key: 'light', ka: 'მსუბუქი', en: 'Light' },
  { key: 'moderate', ka: 'საშუალო', en: 'Moderate' },
  { key: 'intense', ka: 'ინტენსიური', en: 'Intense' },
] as const;

export const MEDICATION_ROUTES = [
  { key: 'oral', ka: 'პერორალური', en: 'Oral' },
  { key: 'topical', ka: 'გარეგანი', en: 'Topical' },
  { key: 'injection', ka: 'ინექცია', en: 'Injection' },
  { key: 'other', ka: 'სხვა', en: 'Other' },
] as const;

export type ProcedureTypeKey = (typeof PROCEDURE_TYPES)[number]['key'];
export type AnesthesiaTypeKey = (typeof ANESTHESIA_TYPES)[number]['key'];
export type IntensityLevelKey = (typeof INTENSITY_LEVELS)[number]['key'];
export type MedicationRouteKey = (typeof MEDICATION_ROUTES)[number]['key'];
